### ISSUE TITLE
别名设置之后就找不到该flutter版本，重装都不行

### ISSUE THREAD

**Issue by wbbbbbbbbbbbbbbbbbb** [xinfeng-tech/fvm#8] opened 2020-06-18 09:34 UTC
我想fvm alias 1.17.3  1.17.3-stable去修改别名
修改之后fvm list只有
1.17.3 => unkonw
1.17.3-stable => unkonw
default => 1.12.13+hotfix.9
latest => 1.12.13+hotfix.9
v1.12.13+hotfix.9-stable => 1.12.13+hotfix.9

然后这个包就像消失了一样，找不到了，重新install也不行，也不能切换
1.我现在要怎么做才能让他恢复出来
2.怎么删除别名
3.具体的flutter目录在哪里，能否手动删除

**Comment by wbbbbbbbbbbbbbbbbbb** [comment] 2020-06-19 02:20
出现了这些警告可以解决吗
Warning! The 'flutter' tool you are currently running is from a different
Flutter repository than the one last used by this package. The repository from
which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/mac/.fvm/versions/1.17.3-stable
  previous reference  : /Users/mac/.fvm/versions/v1.12.13+hotfix.9-stable
This can happen when you have multiple copies of flutter installed. Please check
your system path to verify that you are running the expected version (run
'flutter --version' to see which flutter is on your path).

**Comment by dashixiong91** [comment] 2020-06-22 07:00
Duplicate of #6

**Comment by dashixiong91** [comment] 2020-06-22 07:04
各个版本的flutter安装目录在$HOME/.fvm/versions下，你可以cd进去，查看并手动删除

**Closed as completed** 2020-08-25 04:39 UTC
